### ISSUE TITLE
sampling data from Sine and Double Banana Distribution

### ISSUE THREAD

**Issue by OctoberChang** [dilinwang820/matrix_svgd#1]
Thanks for releasing the experiment code, much appreciated.

I would like to know how to generate data samples from the Sine and Double Banana distributions, which is not specified in the 2d_toy/code/environment.py

I am asking this because we need true data samples and model generated samples to compute MMD, which is plotted in Figure 4 of your NIPS paper.

**Comment by zt95** [comment]
Hi,

Thank you for your interest in our codes.

To get ground truth sample from Sine and Double Banana, we use a stochastic gradient Langevin dynamics(SGLD) sampler to sample 5000 points as our ground truth. Then we use that to compute the MMD distance.

**Comment by zt95** [comment]
I have uploaded a simple code of SGLD in 2d_toy folder, you can take a look.

**Comment by OctoberChang** [comment]
Thanks for the response. I originally thought that there is some kind of data generation process that follows the true data density defined by Sine and Double Banana. Using SGLD with a long horizon step is a fine approximation. Thanks again.
